### PR TITLE
`assertParentPointers` function

### LINKED ISSUE #26: what to do when parent pointers aren't set
There are several functions that require parent pointers to be set to function properly. As of now, we handle cases where parent pointers are not set in an ad-hoc way, particularly, either by failing silently or by throwing an error, but we need to standardize the procedure for a parent not being set across the library.

There are a few options of how to handle cases like these:

1. **Throw an error**: the benefits of throwing errors is two-fold: it let's the author know quickly that they are not properly using Treecle, and it also lowers our codebase complexity as we don't have to try and consider special cases where parent pointers are not set.
2. **Fail silently**: another option is to have a function that requires parent pointers to just return and not do anything, which I see as harmful to authors since it will be harder to debug.
3. **Console warning**: something we've also discussed in the past is making a custom `warn` function which runs `console.warn` in dev environments, which could warn authors that parent pointers are not set without throwing an error.
4. **Try to set parent pointers ourself**: this option is interesting because on one hand, it would be ideal since the authors won't have to worry about error handling or forgetting to set parent pointers. The only issue with this is we do not possess the ability to set relevant parent pointers from a given function if we do not have the root of the tree, which means this wouldn't be a standard across the whole library.

My personal preference would be either option 1 or 3, and more specifically, building an internal function called `checkParentPointers(node)` which would standardize what would happen when no parent pointers are set. Any thoughts here @LeaVerou ?

### PR DESCRIPTION
**Pull request by adamjanicki2**
closes #26

### CODE REVIEW

File: src/util.js [hunk 1]
```diff
@@ -57,3 +59,20 @@ export function setByPath (obj, path, value) {
...
+const message = "Node has no parent pointers set. Call setParent() on the node or updateParents() on an ancestor to add parent pointers to this node";
+
+/**
+ * Check a node to see if it has parent pointers set
+ * @param {Node} node the node to check for parents
+ * @param {"error" | "warn"} severity the severity of the issue
+ * @throws {Error} if the severity is "error" and the node has no parent
+ */
+export function checkParentPointers (node, severity = "error") {
+	if (!getParent(node)) {
```
Comment (LeaVerou) [inline src/util.js:72]: The parent being `null` is not an error, it's just the root of the tree

File: src/util.js [hunk 2]
```diff
@@ -57,3 +59,20 @@ export function setByPath (obj, path, value) {
...
+		if (severity === "error") {
+			throw new Error(message);
```
Comment (LeaVerou) [inline src/util.js:74]: Where is `message` defined?

File: src/replace.js [hunk 3]
```diff
@@ -14,9 +14,7 @@ import { setByPath } from "./util.js";
  */
 export default function replace (child, newChild) {
 	const parentPath = getPath.call(this, child);
-	if (parentPath === undefined) {
-		throw new Error("Cannot replace a child node with no parent pointer. Call setParent() on the node or updateParents() on an ancestor to add parent pointers to this node");
-	}
+	checkParentPointers.call(this, child);
```
Comment (LeaVerou) [inline src/replace.js:17]: So here by making a change to make our codebase more neat, we ended up making the user experience worse, which is an antipattern. The original error was actually more clear. Remember that internal complexity should be preferred over external (user-facing) complexity. Perhaps we can get the best of both worlds by passing the message in, but then it's unclear what benefit the function actually gets us. Perhaps the message could be the part that changes ("Cannot replace a child node with no parent pointer.") and the rest can be added automatically? But does the rest work with every case?

File: src/parents.js [hunk 4]
```diff
@@ -25,7 +25,8 @@ export function setPath (node, parentPath, { force } = {}) {
  * @returns {Node | null | undefined} The parent node, or undefined if the node's parent is unknown
  */
 export function getParent (node) {
-	return parentMap.get(node)?.node;
+	const path = getPath.call(this, node);
```
Comment (LeaVerou) [inline src/parents.js:28]: I guess this is to centralize the logic of how paths are retrieved, but it doesn't seem worth it?

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Hi there, see comments!

File: src/util.js (hunk 1 above)
Comment (adamjanicki2) [reply src/util.js:72]: Yes, force of habit using `!`

File: src/replace.js (hunk 3 above)
Comment (adamjanicki2) [reply src/replace.js:17]: This is currently the only place in our codebase throwing an error, so I think we can do something like `${customMessage} Call setParent() on the node or updateParents() on an ancestor to add parent pointers to this node` to have the last part be consistent

File: src/parents.js (hunk 4 above)
Comment (adamjanicki2) [reply src/parents.js:28]: Yes to centralize, but also because in `getPath` it's doing the work to check `this.root` if no parent pointers are set, so if one of them does it, than the other should too

File: src/util.js (hunk 2 above)
Comment (adamjanicki2) [reply src/util.js:76]: Just above the function signature

File: src/replace.js (hunk 3 above)
Comment (LeaVerou) [reply src/replace.js]: Sounds good. Make sure to cover the case where no message is set.

**Comment by LeaVerou** [comment]
Also, if we don't implement warn yet, let's drop it from the API. There's no reason to have it.

**Comment by adamjanicki2** [comment]
> LGTM. Minor comment, but I'd change the function name, `checkParentPointers()` sounds like a function that checks if they exist and returns a boolean, not something that will produce an error.

Good point, just switched it to `assertParentPointers`

**Comment by adamjanicki2** [comment]
> Also, if we don't implement warn yet, let's drop it from the API. There's no reason to have it.

Sounds good!

**Review by LeaVerou — APPROVED** [review]
